### ISSUE TITLE
Day of Year

### ISSUE THREAD

**Issue by apb2019** [Paul-Reed/node-red-contrib-simpletime#11]
Hi, would you be able to add msg.mydayofyr which would be the number of days since 1st Jan where 1st jan = 1?

**Comment by Paul-Reed** [comment]
Hi, `msg.mydoy` (MyDayOfYear to match MyDayOfMonth) added via https://github.com/Paul-Reed/node-red-contrib-simpletime/commit/0394ba6a874c543af8a363c77a095a38fb91e38b

**Comment by apb2019** [comment]
Hi, tx for the quick implementation
