### ISSUE TITLE
Fails to install on NR 1.3.5

### ISSUE THREAD

**Issue by Barabba11** [Paul-Reed/node-red-contrib-simpletime#21]
Hi I've updated several nodes on my plow but simpletime refuses to install, maybe it's made just for a newer version of NR. how can I overcome this? This is the error:

```
2022-03-12T13:45:48.459Z Install : node-red-contrib-simpletime 2.10.3

2022-03-12T13:45:47.971Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-simpletime@2.10.3
2022-03-12T13:47:59.015Z [out] 
2022-03-12T13:47:59.015Z [out] up to date in 2m
2022-03-12T13:47:59.044Z rc=0

```

on console:
```
Error: Install failed
    at /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/installer.js:214:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
12 Mar 16:47:59 - [error] Error: Install failed

```

npm install node-red-contrib-simpletime doesnt help:
```
pi@RaspbFranco:~/.node-red $ npm install node-red-contrib-simpletime

up to date, audited 832 packages in 2m

71 packages are looking for funding
  run `npm fund` for details

43 vulnerabilities (16 moderate, 25 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

```

Node JS Version

14.17.2
NPM Version

7.19.1
Node-RED Version

1.3.5
Operating System

Raspbian 5.10.48-v7+

**Comment by Barabba11** [comment]
I have solved with npm install node-red-contrib-simpletime@2.10.0

**Comment by Paul-Reed** [comment]
Yes, it failed because you are running an older version of node-RED (v1.3.5) than what is specified in simpletime's package.

When the node-RED scorecard was first  introduced, there was some ambiguity whether supporting pre v2 node-RED systems would result in a lower scorecard mark.
However, it doesn't, so if I get chance this evening I will drop back the requirement and continue to support v1.3.5, which will resolve this problem.

**Comment by Paul-Reed** [comment]
Package has been updated to enable older versions of node-RED to be used... https://github.com/Paul-Reed/node-red-contrib-simpletime/commit/f7f5a4ec422e684befb3dd0f6ad36167b15fbdb0
New version 2.10.4

**Comment by Barabba11** [comment]
Thank you :) I'll test it
