### ISSUE TITLE
Request for long month and long day (January and Saturday)

### ISSUE THREAD

**Issue by skorpioskorpio** [Paul-Reed/node-red-contrib-simpletime#22]
Great node, very useful. However with as many options as there are, full Month name and full Day of week name seem to be absent from the list. Seems like this would be an easy add, they'd just be aliases for "mymonth" and "myday", maybe "mylmonth" and "mylday" (for long). Anyway food for thought.

**Comment by Paul-Reed** [comment]
It sounds like a good idea, but I don't want to overwhelm users with too many options.
Let me take a look over weekend....

**Comment by Paul-Reed** [comment]
Now added to v2.11.1 via 0ba2a04d032ab135da4e4baa69104d7e03fe7515
