### ISSUE TITLE
Add Milliseconds

### ISSUE THREAD

**Issue by nFeno** [Paul-Reed/node-red-contrib-simpletime#8]
Hi,
is it possible to add a _mymilis_ for simpletime node?
Regards

**Comment by Paul-Reed** [comment]
Yes, mymillis added by https://github.com/Paul-Reed/node-red-contrib-simpletime/commit/db9306b96de0dc8178703069c7b9741fdd46ac19

**Comment by pfeno** [comment]
return on the project 
Perhaps is better to pad with 3 like `mil = pad(d.getMilliseconds(), 3);`
