### ISSUE TITLE
padding millisecond correctly

### ISSUE THREAD

**Issue by nFeno** [Paul-Reed/node-red-contrib-simpletime#9]
Hi,
Is it possible to pad milliseconds by 3 like `mil = pad(d.getMilliseconds(), 3);`
_[line 24 in simpletime.js](https://github.com/Paul-Reed/node-red-contrib-simpletime/blob/db9306b96de0dc8178703069c7b9741fdd46ac19/simpletime.js#L24)_

**Comment by Paul-Reed** [comment]
Thanks for reporting.
Fixed by 3d42faae7bcd9ca6c340897e59974fec62c0401e
